server:
  port: 8080
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-server
          uri: http://8.130.111.239:8080
          predicates:
            - Path=/user/**
        - id: user-server
          uri: http://8.130.111.239:8080
          predicates:
            - Path=/verify/**
        - id: article-server
          uri: http://8.130.111.239:8080
          predicates:
            - Path=/article/**
        - id: article-server
          uri: http://8.130.111.239:8080
          predicates:
            - Path=/comment/**
        - id: article-server
          uri: http://8.130.111.239:8080
          predicates:
            - Path=/tag/**
        - id: article-server
          uri: http://8.130.111.239:8080
          predicates:
            - Path=/collection/**
        - id: article-server
          uri: http://8.130.111.239:8080
          predicates:
            - Path=/like/**
        - id: auth-server
          uri: http://8.130.64.58:8080
          predicates:
            - Path=/sso/**
        - id: file-server
          uri: http://8.130.84.120:8080
          predicates:
            - Path=/file/**
