spring:
  application:
    name: auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 8.130.108.66:8848
        username: nacos
        password: Cxcacm1230
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth
    username: cxc_oauth
    password: Cxcacm1230
  redis:
    host: localhost
    password: Cxcacm1230
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
server:
  port: 8080
  servlet:
    context-path: /sso
