spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.64.58:3306/oauth
    username: cxc_oauth
    password: Cxcacm1230
  redis:
    host: 8.130.64.58
    password: Cxcacm1230
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
server:
  port: 8080
  servlet:
    context-path: /sso
